apiVersion: v1
kind: Service
metadata:
  labels:
    app: potato-facts
  name: potato-facts-external

spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: gate-tcp
    port: 80
    protocol: TCP
    targetPort: 8086
  selector:
    app: potato-facts
  type: LoadBalancer















