name: Rightsize my deployment my latest version

on: workflow_dispatch
  #repository_dispatch:
  #  types: resize
jobs:
  rightSize:
    name: Calls the callback being passed in
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: getSizingApiResponse
        id: getReqs
        uses: fjogeleit/http-request-action@master
        with:
          url: "http://a6299b5747b7b4a698f4098a263ea0a7-1252398275.us-east-2.elb.amazonaws.com:9090/model/savings/requestSizing?filterNamespaces=borealis-prod&filterContainer=potato-facts&algorithm=max-headroom"
          method: "GET"
      - name: Show mresponse
        run: 'echo "${{ steps.getReqs.outputs.response }}"'
      - name: write to file
        run: 'echo "${{ steps.getReqs.outputs.response }}" > /kubeCost.json'
      - name: extract CPU sizing
        uses: sergeysova/jq-action@v2
        id: cpuSizing
        with:
          cmd: "echo '${{ steps.getReqs.outputs.response }}' > /kubeCost.json && jq '[.controllers[].target.cpuCores]|max' /kubeCost.json -r"
      - name: extract RAM sizing
        uses: sergeysova/jq-action@v2
        id: ramSizing
        with:
          cmd: "${{ steps.getReqs.outputs.response }}' > /kubeCost.json && jq '[.controllers[].target.ramBytes]|max'  /kubeCost.json -r"
      - name: Show my new requests
        run: 'echo "new cpu request ${{ steps.cpuSizing.outputs.value }}, new memory request ${{ steps.ramSizing.outputs.value }}"'
